spring:
  datasource:
    url:  jdbc:mysql://192.168.11.128:3306/interview?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  aop:
    proxy-target-class: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #mybatis一级缓存范围
    local-cache-scope: session
    #开启二级缓存
    cache-enabled: true
    #打印sql语句的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl